name:                sober
version:             0.1.0.0
github:              "https://github.com/oderwat/sober"
license:             BSD3
author:              "Hans Raaf"
maintainer:          "hara@oderwat.de"
copyright:           "2019 Hans Raaf"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sober#readme>

dependencies:
- base >= 4.7 && < 5
- process >= 1.6.3 && < 2.0
- split >= 0.2.3 && < 1.0
- network-uri >= 2.6.1 && < 3.0

library:
  source-dirs: src

executables:
  sober-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sober

tests:
  sober-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sober
